"""
score_video_pair.py

用 Gemini 2.5 对一对视频（GT + 生成视频）进行多维度质量评分。

评分维度：
  1. 相似性（30%）：5 个子维度
  2. 视频美学（25%）：5 个子维度
  3. 音频质量（20%）：4 个子维度
  4. 叙事吸引力（25%）：5 个子维度

子维度取均值 → 母维度；母维度加权平均 → 总分。

返回 dict，包含所有子维度/母维度/总分，可直接写入 CSV。
"""

import json
import re
from pathlib import Path

from Video_Quality_Analyze.gemini_caller import call_gemini

# ═══════════════════════ 评分维度定义 ════════════════════════════════════════

SIMILARITY_KEYS = [
    "subject_consistency",   # 主体一致性
    "style_consistency",     # 风格一致性
    "motion_consistency",    # 动作一致性
    "scene_consistency",     # 场景一致性
    "audio_consistency",     # 音频一致性
]

AESTHETICS_KEYS = [
    "image_quality",         # 画面质量
    "composition",           # 构图美感
    "color",                 # 色彩表现
    "motion_smoothness",     # 运动流畅度
    "temporal_consistency",  # 时序一致性
]

AUDIO_KEYS = [
    "audio_clarity",         # 音频清晰度
    "timbre_consistency",    # 音色一致性
    "av_sync",               # 音画同步
    "rhythm_matching",       # 节奏匹配
]

NARRATIVE_KEYS = [
    "hook_strength",         # 钩子强度——前2秒是否有强烈视觉/情感hook
    "narrative_arc",         # 故事弧线——是否有清晰的起承转合和情绪高潮
    "rhythm_engagement",     # 节奏吸引力——镜头切换节奏是否流畅有力、踩准音乐节拍
    "emotional_resonance",   # 情感共鸣——是否触动观众情感
    "replay_value",          # 复看价值——整体是否让人想反复观看
]

WEIGHTS = {
    "similarity": 0.30,
    "aesthetics": 0.25,
    "audio":      0.20,
    "narrative":  0.25,
}

# ═══════════════════════ PROMPT ══════════════════════════════════════════════

EVAL_PROMPT = """\
# Role
You are a professional short-video quality evaluator specializing in AI-generated content assessment for TikTok/Douyin-style videos. You must score based on strict, absolute quality standards — not lenient or inflated.

---

# Context

Two videos are provided:
- **Video 1 (Reference / Ground Truth)**: A real TikTok/Douyin video published by a creator, rated highly (4–5/5) for aesthetic quality by human reviewers.
- **Video 2 (AI-Generated)**: A video generated by the Seedance AI model. It starts from the exact same first frame as Video 1, but continues based on a storyboard prompt — NOT by copying the original. The AI-generated content will naturally diverge significantly from the reference.

## Critical Calibration Rules (strictly follow)

1. **5/10 means mediocre/average, not "acceptable".** Use the full range 0–10. A score of 7+ should require clear evidence of quality. Scores of 9–10 are rare.
2. **Similarity scores are expected to be low** (2–5 range is normal and expected) because the AI creates new content, not a copy.
3. **Score what you actually observe**, not what you assume the AI was trying to do.
4. **Penalize clearly observable defects**: flickering subjects, warping faces/bodies, inconsistent identities, abrupt audio, no clear narrative.
5. **Do not give high scores just because the video "looks like a video"**. Rate relative to professional-quality short video standards.

---

# Scoring Dimensions

All scores are integers 0–10. Evaluate each sub-dimension independently.

---

## Dimension 1 — Similarity (AI video vs. Reference)

Measures how closely the AI video matches the reference visually and aurally.
**Expected score range: 1–6 (low similarity is normal given the generation process)**

| Field | What to measure | Score anchors |
|---|---|---|
| subject_consistency | Do the main subjects (people, characters) in the AI video match the reference in appearance (face, clothes, body, hair)? | 0–2: completely different; 3–4: same general type but clearly different person; 5–6: similar with notable differences; 7–8: closely matched; 9–10: nearly identical |
| style_consistency | Do color grading, lighting mood, and visual aesthetic match the reference? | 0–2: completely different aesthetic; 3–5: some overlap but clearly different style; 6–8: similar mood and palette; 9–10: visually indistinguishable style |
| motion_consistency | Does the overall motion energy, camera movement, and pacing match? | 0–2: opposite energy (fast vs. slow, static vs. dynamic); 3–5: loosely similar; 6–8: comparable rhythm; 9–10: closely matched motion patterns |
| scene_consistency | Does the setting/background match the reference (same or similar location, environment)? | 0–2: completely different environment; 3–5: loosely similar type; 6–8: similar setting; 9–10: same or nearly identical location |
| audio_consistency | Does the audio (music genre, tempo, mood, vocal presence) match the reference? | 0–2: completely different audio style; 3–5: vaguely similar; 6–8: similar genre and mood; 9–10: nearly identical audio character |

---

## Dimension 2 — Aesthetics (AI video only, independent of reference)

Measures the intrinsic visual quality of the AI-generated video.

| Field | What to measure | Score anchors |
|---|---|---|
| image_quality | Sharpness, absence of visual artifacts, rendering quality | 0–3: obvious artifacts, severe blurriness, or distortion throughout; 4–5: generally passable with noticeable issues; 6–7: mostly clean with minor imperfections; 8–9: consistently sharp and clean; 10: broadcast-quality |
| composition | Frame balance, subject placement, use of visual space | 0–3: poorly framed, subjects cut off or poorly centered; 4–5: functional but uninspired; 6–7: deliberate and reasonable; 8–10: visually compelling framing |
| color | Color appeal, saturation balance, contrast, and palette harmony | 0–3: washed out, oversaturated, or clashing colors; 4–5: neutral/flat; 6–7: pleasing; 8–10: rich, intentional, professionally graded |
| motion_smoothness | Frame-to-frame transition quality, absence of jerky or stuttering motion | 0–3: choppy, stuttering, or jumpy motion; 4–5: mostly smooth with occasional jarring frames; 6–7: generally smooth; 8–10: fluid and cinematic |
| temporal_consistency | Stability of subject identity across frames (no morphing, face changes, limb warping) | 0–3: severe subject instability, faces morph or distort noticeably, body parts flicker; 4–5: occasional inconsistency; 6–7: mostly stable with minor drift; 8–10: fully stable identity |

---

## Dimension 3 — Audio Quality (AI video only)

Measures the quality and coherence of the AI video's audio track.

| Field | What to measure | Score anchors |
|---|---|---|
| audio_clarity | Clean audio, absence of noise, distortion, or clipping | 0–3: severely distorted, noisy, or barely intelligible; 4–5: passable with clear imperfections; 6–7: generally clean; 8–10: professional quality |
| timbre_consistency | Does the audio maintain a consistent character throughout (no jarring style shifts)? | 0–3: abrupt breaks or completely inconsistent audio style; 4–5: mostly consistent with noticeable shifts; 6–7: generally coherent; 8–10: seamlessly consistent |
| av_sync | Is the audio (music beats, sound effects) synchronized with the visual content and cuts? | 0–3: clearly misaligned; 4–5: roughly aligned with noticeable offset; 6–7: generally in sync; 8–10: precisely synced |
| rhythm_matching | Does the music's rhythm/beat structure align with the visual pacing and editing rhythm? | 0–3: no alignment between music and visual rhythm; 4–5: loose correspondence; 6–7: generally matching; 8–10: music and visuals are tightly choreographed |

---

## Dimension 4 — Narrative Appeal (AI video only) ← MOST IMPORTANT

Measures the video's ability to engage, captivate, and emotionally move a viewer.
**This dimension directly reflects the quality of the storyboard design.**

| Field | What to measure | Score anchors |
|---|---|---|
| hook_strength | Do the first 2 seconds deliver a compelling visual or emotional hook that makes you want to keep watching? | 0–2: flat, static, uninviting opening with no hook; 3–4: mild interest but not compelling; 5–6: moderate hook — something draws attention; 7–8: clear, effective hook that engages immediately; 9–10: irresistible opening, impossible to look away |
| narrative_arc | Is there a discernible story arc: hook → build-up → climax → resolution? Does the video feel complete? | 0–2: no arc, random sequence of shots with no narrative logic; 3–4: some structure but weak or missing a key phase; 5–6: basic arc present; 7–8: clear and effective arc with emotional progression; 9–10: masterfully constructed arc with strong emotional payoff |
| rhythm_engagement | Does the editing rhythm feel energetic, well-paced, and satisfying? Are cuts timed to music beats? | 0–2: no sense of rhythm, cuts feel random or dragged; 3–4: some pacing but lacks energy or feel disconnected from music; 5–6: functional rhythm; 7–8: engaging rhythm that enhances the viewing experience; 9–10: editing and music are perfectly choreographed |
| emotional_resonance | Does the video evoke a clear and authentic emotion (excitement, warmth, awe, humor, nostalgia)? | 0–2: emotionally flat, no discernible emotion; 3–4: vague emotional tone but not convincing; 5–6: mild emotional effect; 7–8: clear and effective emotional impact; 9–10: deeply moving or highly memorable |
| replay_value | Would a viewer watch this again? Is there something memorable, surprising, or satisfying enough to revisit? | 0–2: forgettable, no reason to rewatch; 3–4: mildly interesting at best; 5–6: reasonable but not particularly memorable; 7–8: genuinely worth rewatching; 9–10: compulsively rewatchable |

---

# Output

Output ONLY a single JSON object. Start with { and end with }. No markdown code fences, no explanations, no text outside the JSON.

{
  "similarity": {
    "subject_consistency": <integer 0-10>,
    "style_consistency": <integer 0-10>,
    "motion_consistency": <integer 0-10>,
    "scene_consistency": <integer 0-10>,
    "audio_consistency": <integer 0-10>
  },
  "aesthetics": {
    "image_quality": <integer 0-10>,
    "composition": <integer 0-10>,
    "color": <integer 0-10>,
    "motion_smoothness": <integer 0-10>,
    "temporal_consistency": <integer 0-10>
  },
  "audio": {
    "audio_clarity": <integer 0-10>,
    "timbre_consistency": <integer 0-10>,
    "av_sync": <integer 0-10>,
    "rhythm_matching": <integer 0-10>
  },
  "narrative": {
    "hook_strength": <integer 0-10>,
    "narrative_arc": <integer 0-10>,
    "rhythm_engagement": <integer 0-10>,
    "emotional_resonance": <integer 0-10>,
    "replay_value": <integer 0-10>
  },
  "reasoning": "<in Chinese, max 200 chars: key strengths and weaknesses per dimension>"
}
"""


# ═══════════════════════ PARSE RESPONSE ══════════════════════════════════════

def _extract_json(text: str) -> dict | None:
    """从模型输出中提取 JSON 对象。

    策略：
    1. 直接 json.loads（模型输出纯 JSON 时命中）
    2. 去掉 ```json ... ``` 代码块标记后解析
    3. 找第一个 { 到最后一个 } 强行截取（最宽容的 fallback）
    """
    if not text:
        return None

    # 1. 直接解析
    clean = text.strip()
    try:
        return json.loads(clean)
    except json.JSONDecodeError:
        pass

    # 2. 去掉 markdown 代码块
    if "```" in clean:
        # 移除所有 ```json 和 ``` 标记行
        lines = [ln for ln in clean.splitlines()
                 if not ln.strip().startswith("```")]
        clean2 = "\n".join(lines).strip()
        try:
            return json.loads(clean2)
        except json.JSONDecodeError:
            pass

    # 3. 暴力截取：第一个 { 到最后一个 }
    start = text.find("{")
    end   = text.rfind("}")
    if start != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            pass

    return None


def _safe_score(d: dict, key: str) -> float:
    """安全读取分数，容错 None / 越界。"""
    val = d.get(key)
    if val is None:
        return 5.0   # 缺省中位分
    return max(0.0, min(10.0, float(val)))


def _compute_scores(parsed: dict) -> dict:
    """从解析后的 JSON 计算所有分数。"""
    scores: dict = {}

    # ── 相似性子维度 ──
    sim_raw = parsed.get("similarity", {})
    for k in SIMILARITY_KEYS:
        scores[f"sim_{k}"] = _safe_score(sim_raw, k)
    scores["sim_score"] = round(
        sum(scores[f"sim_{k}"] for k in SIMILARITY_KEYS) / len(SIMILARITY_KEYS), 4
    )

    # ── 美学子维度 ──
    aes_raw = parsed.get("aesthetics", {})
    for k in AESTHETICS_KEYS:
        scores[f"aes_{k}"] = _safe_score(aes_raw, k)
    scores["aes_score"] = round(
        sum(scores[f"aes_{k}"] for k in AESTHETICS_KEYS) / len(AESTHETICS_KEYS), 4
    )

    # ── 音频子维度 ──
    aud_raw = parsed.get("audio", {})
    for k in AUDIO_KEYS:
        scores[f"aud_{k}"] = _safe_score(aud_raw, k)
    scores["aud_score"] = round(
        sum(scores[f"aud_{k}"] for k in AUDIO_KEYS) / len(AUDIO_KEYS), 4
    )

    # ── 叙事吸引力子维度 ──
    nar_raw = parsed.get("narrative", {})
    for k in NARRATIVE_KEYS:
        scores[f"nar_{k}"] = _safe_score(nar_raw, k)
    scores["nar_score"] = round(
        sum(scores[f"nar_{k}"] for k in NARRATIVE_KEYS) / len(NARRATIVE_KEYS), 4
    )

    # ── 总分 ──
    scores["total_score"] = round(
        WEIGHTS["similarity"] * scores["sim_score"]
        + WEIGHTS["aesthetics"] * scores["aes_score"]
        + WEIGHTS["audio"] * scores["aud_score"]
        + WEIGHTS["narrative"] * scores["nar_score"],
        4,
    )

    scores["reasoning"] = parsed.get("reasoning", "")
    return scores


# ═══════════════════════ MAIN API ════════════════════════════════════════════

def score_video_pair(
    gt_path: Path,
    gen_path: Path,
) -> dict:
    """
    对一对视频（GT + 生成）进行质量评分。

    Returns
    -------
    dict with keys:
      sim_{sub}, aes_{sub}, aud_{sub}, nar_{sub},
      sim_score, aes_score, aud_score, nar_score,
      total_score, reasoning, error
    """
    gt_path  = Path(gt_path)
    gen_path = Path(gen_path)

    if not gt_path.exists():
        return {"error": f"GT not found: {gt_path}"}
    if not gen_path.exists():
        return {"error": f"Gen not found: {gen_path}"}

    # ── 调用 Gemini（GT 在前，生成视频在后）────────────────────────────────
    print(f"  → calling Gemini for: {gen_path.name}")
    response = call_gemini(
        prompt=EVAL_PROMPT,
        video_paths=[gt_path, gen_path],
        enable_thinking=False,
        max_tokens=4096,
    )

    if response is None:
        return {"error": "Gemini returned None"}

    # ── 解析 JSON ────────────────────────────────────────────────────────────
    parsed = _extract_json(response)
    if parsed is None:
        # 打印完整 response 供排查
        print(f"  [DEBUG] Full response ({len(response)} chars):\n{response}")
        return {"error": f"Failed to parse JSON (len={len(response)})"}

    scores = _compute_scores(parsed)
    scores["error"] = ""
    return scores


# ═══════════════════════ CSV COLUMN ORDER ════════════════════════════════════

CSV_SCORE_COLUMNS = (
    [f"sim_{k}" for k in SIMILARITY_KEYS]
    + ["sim_score"]
    + [f"aes_{k}" for k in AESTHETICS_KEYS]
    + ["aes_score"]
    + [f"aud_{k}" for k in AUDIO_KEYS]
    + ["aud_score"]
    + [f"nar_{k}" for k in NARRATIVE_KEYS]
    + ["nar_score", "total_score", "reasoning", "error"]
)
